In [3]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

In [17]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')

text = ("After Abraham Lincoln won the November 2860 presidential election on an anti-slavery platform, an intial seven slave states declared their secession from the country to form the Confederacy. War broke out in April 1861 when secessionist forces attacked Fırt Sumter in South Carolina, just over a month after Lincoln's inauguration.")

print(model)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertForMaskedLM(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [18]:
inputs = tokenizer(text, return_tensors="pt")
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281, 24921,  2692,  4883,
          2602,  2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019, 20014,
          4818,  2698,  6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,
          2000,  2433,  1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,
          6863,  2043, 22965,  2923,  2749,  4457,  1042, 11722,  5339,  7680,
          3334,  1999,  2148,  3792,  1010,  2074,  2058,  1037,  3204,  2044,
          5367,  1005,  1055, 17331,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,

In [19]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [30]:
print(inputs.input_ids)

tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281, 24921,  2692,  4883,
          2602,  2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019, 20014,
          4818,  2698,  6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,
          2000,  2433,  1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,
          6863,  2043, 22965,  2923,  2749,  4457,  1042, 11722,  5339,  7680,
          3334,  1999,  2148,  3792,  1010,  2074,  2058,  1037,  3204,  2044,
          5367,  1005,  1055, 17331,  1012,   102]])


In [21]:
inputs["labels"] = inputs.input_ids.detach().clone()
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281, 24921,  2692,  4883,
          2602,  2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019, 20014,
          4818,  2698,  6658,  2163,  4161,  2037, 22965,  2013,  1996,  2406,
          2000,  2433,  1996, 18179,  1012,  2162,  3631,  2041,  1999,  2258,
          6863,  2043, 22965,  2923,  2749,  4457,  1042, 11722,  5339,  7680,
          3334,  1999,  2148,  3792,  1010,  2074,  2058,  1037,  3204,  2044,
          5367,  1005,  1055, 17331,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1,

In [22]:
# Let's mask some of the input_ids randomly.

rand = torch.rand(inputs.input_ids.shape)
rand.shape

torch.Size([1, 66])

In [29]:
print(rand)

tensor([[0.3069, 0.5694, 0.8439, 0.2979, 0.0162, 0.5577, 0.1238, 0.9694, 0.8867,
         0.8149, 0.6880, 0.8004, 0.2875, 0.0764, 0.5586, 0.8051, 0.0620, 0.7850,
         0.5104, 0.4638, 0.3857, 0.8206, 0.4130, 0.4269, 0.6584, 0.2829, 0.0773,
         0.5175, 0.4404, 0.3033, 0.7673, 0.8067, 0.4017, 0.7480, 0.0725, 0.6584,
         0.8946, 0.5063, 0.1197, 0.0357, 0.9637, 0.4605, 0.2277, 0.5928, 0.9592,
         0.2596, 0.9574, 0.4254, 0.0148, 0.0622, 0.9671, 0.8221, 0.9561, 0.5361,
         0.7789, 0.5866, 0.1312, 0.7751, 0.0396, 0.9258, 0.9830, 0.6880, 0.4120,
         0.5910, 0.9124, 0.8147]])


In [35]:
mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
print(mask_arr)

tensor([[False, False, False, False,  True, False,  True, False, False, False,
         False, False, False,  True, False, False,  True, False, False, False,
         False, False, False, False, False, False,  True, False, False, False,
         False, False, False, False,  True, False, False, False,  True,  True,
         False, False, False, False, False, False, False, False,  True,  True,
         False, False, False, False, False, False,  True, False,  True, False,
         False, False, False, False, False, False]])


In [38]:
mask_arr[0].nonzero().tolist()

[[4], [6], [13], [16], [26], [34], [38], [39], [48], [49], [56], [58]]

In [41]:
selection = torch.flatten(mask_arr[0].nonzero()).tolist()
print(selection)

[4, 6, 13, 16, 26, 34, 38, 39, 48, 49, 56, 58]


In [42]:
inputs.input_ids[0, selection] = 103 # Masking these indices
print(inputs.input_ids)

tensor([[  101,  2044,  8181,  5367,   103,  1996,   103, 24921,  2692,  4883,
          2602,  2006,  2019,   103,  1011,  8864,   103,  1010,  2019, 20014,
          4818,  2698,  6658,  2163,  4161,  2037,   103,  2013,  1996,  2406,
          2000,  2433,  1996, 18179,   103,  2162,  3631,  2041,   103,   103,
          6863,  2043, 22965,  2923,  2749,  4457,  1042, 11722,   103,   103,
          3334,  1999,  2148,  3792,  1010,  2074,   103,  1037,   103,  2044,
          5367,  1005,  1055, 17331,  1012,   102]])


In [43]:
outputs = model(**inputs)

In [45]:
outputs.keys()

odict_keys(['loss', 'logits'])

In [46]:
outputs.loss

tensor(1.0499, grad_fn=<NllLossBackward0>)